name: Frontend CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Run tests
        run: |
          pnpm test
          pnpm test:coverage

      - name: Build
        run: pnpm build

      - name: Generate coverage badge
        run: |
          COVERAGE=$(jq '.total.lines.pct' coverage/coverage-summary.json)
          COVERAGE_FORMATTED=$(printf "%.2f%%" $COVERAGE)

          # Determine badge color
          color=$(echo "$COVERAGE < 50" | bc)
          BADGE_COLOR=$([[ "$color" == "1" ]] && echo "red" || echo "brightgreen")

          # Create badge URL
          BADGE_URL="https://img.shields.io/badge/Coverage-${COVERAGE_FORMATTED}-${BADGE_COLOR}"

          # Update README (optional, only if in same repo)
          sed -i "s|<!-- FRONTEND_COVERAGE_BADGE -->|![Frontend Coverage](${BADGE_URL})|g" README.md

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Deploy to Vercel (optional)
        run: npx vercel deploy --prod
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
