name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run backend tests
        working-directory: ./backend
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/shortlink
          NODE_ENV: test
          BASE_URL: http://short.est
        run: |
          pnpm test
          pnpm test:coverage

      - name: Run frontend tests
        working-directory: ./frontend
        run: |
          pnpm test
          pnpm test:coverage

      - name: Generate coverage badges
        run: |
          # Backend coverage
          BACKEND_COVERAGE=$(grep -oE '"total":{[^}]*"lines":{[^}]*"pct":[0-9.]+' backend/coverage/coverage-summary.json | grep -oE '[0-9.]+%' | head -1)
          echo "BACKEND_COVERAGE=${BACKEND_COVERAGE}" >> $GITHUB_ENV

          # Frontend coverage
          FRONTEND_COVERAGE=$(grep -oE '"total":{[^}]*"lines":{[^}]*"pct":[0-9.]+' frontend/coverage/coverage-summary.json | grep -oE '[0-9.]+%' | head -1)
          echo "FRONTEND_COVERAGE=${FRONTEND_COVERAGE}" >> $GITHUB_ENV

      - name: Update README with coverage badges
        run: |
          sed -i "s|<!-- BACKEND_COVERAGE_BADGE -->|![Backend Coverage](https://img.shields.io/badge/Backend_Coverage-${env:BACKEND_COVERAGE}-brightgreen)|g" README.md
          sed -i "s|<!-- FRONTEND_COVERAGE_BADGE -->|![Frontend Coverage](https://img.shields.io/badge/Frontend_Coverage-${env:FRONTEND_COVERAGE}-brightgreen)|g" README.md
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git commit -m "Update test coverage badges [skip ci]" || echo "No changes to commit"
          git push
