name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: shortlink
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "pnpm"

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run backend tests
        working-directory: ./backend
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/shortlink
          NODE_ENV: test
          BASE_URL: http://short.est
        run: |
          pnpm test
          pnpm test:coverage

      - name: Run frontend tests
        working-directory: ./frontend
        run: |
          pnpm test
          pnpm test:coverage

      - name: Generate coverage badges
        run: |
          BACKEND_COVERAGE=$(jq -r '.total.lines.pct' backend/coverage/coverage-summary.json)
          echo "BACKEND_COVERAGE=${BACKEND_COVERAGE}" >> $GITHUB_ENV

          FRONTEND_COVERAGE=$(jq -r '.total.lines.pct' frontend/coverage/coverage-summary.json)
          echo "FRONTEND_COVERAGE=${FRONTEND_COVERAGE}" >> $GITHUB_ENV

      - name: Update README with coverage badges
        run: |
          sed -i "s|<!-- BACKEND_COVERAGE_BADGE -->|![Backend Coverage](https://img.shields.io/badge/Backend_Coverage-${BACKEND_COVERAGE}-brightgreen)|g" README.md
          sed -i "s|<!-- FRONTEND_COVERAGE_BADGE -->|![Frontend Coverage](https://img.shields.io/badge/Frontend_Coverage-${FRONTEND_COVERAGE}-brightgreen)|g" README.md
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git commit -m "Update test coverage badges [skip ci]" || echo "No changes to commit"
          git push
