name: CI Pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run backend tests
        working-directory: ./backend
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/shortlink
          NODE_ENV: test
          BASE_URL: http://short.est
        run: |
          pnpm test
          pnpm test:coverage

      - name: Run frontend tests
        working-directory: ./frontend
        run: |
          pnpm test
          pnpm test:coverage

      - name: Generate coverage badges
        run: |
          # Backend coverage
          BACKEND_COVERAGE=$(jq '.total.lines.pct' backend/coverage/coverage-summary.json)
          BACKEND_COVERAGE_FORMATTED=$(printf "%.2f%%" $BACKEND_COVERAGE)
          echo "Backend Coverage: $BACKEND_COVERAGE_FORMATTED"

          # Frontend coverage
          FRONTEND_COVERAGE=$(jq '.total.lines.pct' frontend/coverage/coverage-summary.json)
          FRONTEND_COVERAGE_FORMATTED=$(printf "%.2f%%" $FRONTEND_COVERAGE)
          echo "Frontend Coverage: $FRONTEND_COVERAGE_FORMATTED"

          # Determine badge color based on coverage percentage
          backend_color=$(echo "$BACKEND_COVERAGE < 50" | bc)
          frontend_color=$(echo "$FRONTEND_COVERAGE < 50" | bc)

          BACKEND_BADGE_COLOR=$([[ "$backend_color" == "1" ]] && echo "red" || echo "brightgreen")
          FRONTEND_BADGE_COLOR=$([[ "$frontend_color" == "1" ]] && echo "red" || echo "brightgreen")

          # Update README with dynamic badges
          sed -i "s|<!-- BACKEND_COVERAGE_BADGE -->|![Backend Coverage](https://img.shields.io/badge/Backend_Coverage-${BACKEND_COVERAGE_FORMATTED}-${BACKEND_BADGE_COLOR})|g" README.md
          sed -i "s|<!-- FRONTEND_COVERAGE_BADGE -->|![Frontend Coverage](https://img.shields.io/badge/Frontend_Coverage-${FRONTEND_COVERAGE_FORMATTED}-${FRONTEND_BADGE_COLOR})|g" README.md

      - name: Commit and push README changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.md
          git commit -m "Update coverage badges [skip ci]" || exit 0
          git push
